### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by tleylan** [IPGeolocation/ip-geolocation-api-typescript-sdk#5]
I notice that the code is 3 years old and my tests indicate that it isn't working per the documentation. I suppose it could be something I'm doing but it looks unlikely.

I've never seen an import statement give the complete path but even so the following one is never found.

import { GeolocationParams } from './node_modules/ip-geolocation-api-sdk-typescript/GeolocationParams';

Is anyone using this? Thanks.

**Comment by ejaz-ahmed** [comment]
Hi @tleylan we haven't updated this for long. I'm not sure if we'll be able to update it or not.

**Comment by tleylan** [comment]
Thanks for the reply. I've found an alternative library so this isn't an issue.

**Comment by ejaz-ahmed** [comment]
Hy @tleylan can you please point me out to that library?

**Comment by tleylan** [comment]
I probably should have written "an alternative service". https://www.bigdatacloud.com/ip-geolocation-apis/ip-address-geolocation-api
